Serilog:
  Using: [ "Serilog.Sinks.Console", "Serilog.Sinks.Loki" ]
  MinimumLevel:
    Default: Information
    Override:
      SS14: Debug
      Microsoft: "Warning"
      Microsoft.Hosting.Lifetime: "Information"
      Microsoft.AspNetCore: Warning

  WriteTo:
    - Name: Console
      Args:
        Theme: Serilog.Sinks.SystemConsole.Themes.AnsiConsoleThemes::Code, Serilog.Sinks.Console
        OutputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3} {SourceContext}] {Message:lj}{NewLine}{Exception}"

  Enrich: [ "FromLogContext" ]

  #Loki:
  #  Address: "http://localhost:3100"
  #  Name: "Test"

ForwardProxies:
  - 127.0.0.1

AllowedHosts: "*"

Account:
  UsernameChangeDays: 30

OpenId:
  Server:
    AuthorizationEndpointUris: [ Identity/Account/Consent ]
    TokenEndpointUris: [ connect/token ]
    EndSessionEndpointUris: [ connect/endsession ]
    UserInfoEndpointUris: [ connect/userinfo ]
    IntrospectionEndpointUris: [ connect/introspect ]
    GrantTypes:
    - authorization_code
    - refresh_token
    ResponseTypes: [ code ]
    Scopes: [ openid, profile, email, roles, offline_access ]
